site_name: Hotel CLARIS
site_url: https://honzasvacek.github.io/hotelclaris
site_description: "Hotel CLARIS - Luxury accommodation in Prague with modern rooms, excellent service, and convenient location"
theme:
  name: material
  icon:
    alternate: fontawesome/solid/globe
  custom_dir: overrides
  language: en
  font: 
    text: Merriweather Sans
  logo: assets/peters.png
  favicon: assets/petersFavicon.ico
  features:
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.sections 
    - toc.follow
    - navigation.top
    - search.suggest
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: deep orange
      accent: blue

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: orange
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: deep orange
      accent: blue

      # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: orange
      accent: deep purple

extra_css:
  - assets/stylesheets/imagezoom.css
  - assets/stylesheets/gallery.css
  - assets/stylesheets/reservationform.css
  - assets/stylesheets/hero.css
  - assets/stylesheets/hotelrooms.css
extra_javascript:
  - javascripts/reservation.js
  - javascripts/hero-rotation.js
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.snippets:
      base_path: 'docs/snippets'
copyright: 'Hotel Claris, Slezská 26, Praha 2 | +420 775 712 882 | E-mail: reservation@petrs.cz | www.hotelclaris.cz'
extra:
  checkin_time: "14:00"
  checkout_time: "11:00"
  hotel_name: "Hotel"
  social:
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/ClarisHotel
    - icon: fontawesome/solid/paper-plane
      link: mailto:<reservation@petrs.cz>
  generator: false
  consent:
    title: Cookie consent
    description: >-

      We use cookies and visitor tracking to improve the functionality of our website. To customize content to your preferences, we also use optional tracking for analytics and marketing purposes. This means better content and offers.
    actions: 
      - accept
      - reject
      - manage
    cookies:
      analytics:
        name: Google Analytics
        checked: true
      github:
        name: Github
        checked: true

plugins:
  - glightbox:
      effect: zoom
      slide_effect: zoom
      zoomable: true
      draggable: true
  - search
  - macros
  - i18n:
      docs_structure: suffix
      languages:
        - locale: en
          default: true
          name: 🇬🇧 English
          build: true
        - locale: cs
          name: 🇨🇿 Česky
          build: true
        - locale: de 
          name: 🇩🇪 Deutsch
          build: true
        

